services:
  meshtastic-mqtt:
    container_name: meshtastic-mqtt
    depends_on:
      - mariadb
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /app/docker/mqtt.sh
    links:
      - mariadb
    env_file:
      - ../.env

  meshmap:
    container_name: meshmap
    depends_on:
      - mariadb
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /app/docker/webapp.sh
    ports:
      - 8080:8080/tcp
    links:
      - mariadb
    env_file:
      - ../.env

  mariadb:
    container_name: mariadb
    image: bitnami/mariadb
    ports:
      - 3306:3306/tcp
    env_file:
      - ../.env
    volumes:
      - mariadb_data:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
      start_interval: 5s

volumes:
  mariadb_data:
